import Image from "next/image";
import Link from "next/link";
import { ButtonHTMLAttributes } from "react";
import Head from "next/head";
import { log } from "console";
import HomeHero from "./assets/component/section/homehero";
import Expertise from "./assets/component/section/expertise";
import Experience from "./assets/component/section/experience";
import Porto from "./assets/component/section/porto";
import Footer from "./assets/component/section/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Abdul Qhodir Zaelany Portofolio</title>
        <meta name="description" content="generated by qodirtok" />
      </Head>

      <main className="bg-white " style={{ fontFamily: "Poppins" }}>
        <section
          className="min-h-full px-[16px] md:px-[120px] lg:px-[120px] "
          style={{ backgroundColor: "#F7F9FF" }}
        >
          <HomeHero />
        </section>
        <section
          id="Experience"
          className="min-h-full py-[140px] px-[16px] md:px-[120px] lg:px-[120px] flex flex-col gap-[80px]"
          style={{ backgroundColor: "#FFFFFF" }}
        >
          <Expertise />
        </section>
        <section
          id="Work"
          className="min-h-full flex flex-col px-[16px] sm:px-[16px] md:px-[120px] lg:px-[120px] md:py-[140px] lg:py-[140px] gap-[80px]"
          style={{ backgroundColor: "#F7F9FF" }}
        >
          <Experience />
        </section>

        <section
          id="Contact"
          className="min-h-full py-[140px] px-[16px] md:px-[120px] lg:px-[120px] flex flex-col gap-[80px]"
          style={{ backgroundColor: "#FFFFFF" }}
        >
          <Porto />
        </section>

        <footer className="flex flex-col justify-center items-center py-[40px] bg-[#FAFBFC]">
          <Footer />
        </footer>
      </main>
    </div>
  );
}
